version: 1
disable_existing_loggers: False

formatters:
    simple:
        format: '%(asctime)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    colorful:
        class: colorlog.ColoredFormatter
        format: '%(log_color)s%(asctime)s - %(levelname)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
        log_colors:
            DEBUG:    'bold_blue'
            INFO:     'bold_green'
            WARNING:  'bold_yellow'
            ERROR:    'bold_red'
            CRITICAL: 'bold_purple'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: colorful
        stream: ext://sys.stdout

    file:
        class: logging.FileHandler
        level: INFO
        formatter: simple
        filename: audio_preprocessing.log
        mode: a

    error_file:
        class: logging.FileHandler
        level: ERROR
        formatter: simple
        filename: error.log
        mode: a

loggers:
    development:
        level: DEBUG
        handlers: [console]
        propagate: no

    staging:
        level: INFO
        handlers: [console, file]
        propagate: no

    production-local:
        level: INFO
        handlers: [console, error_file]
        propagate: no

    production:
        level: WARNING
        handlers: [console]
        propagate: no

root:
    level: DEBUG
    handlers: [console]